"use client";

import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import MenuTable,{type CellRef} from "@/components/MenuTable";
import ExecutionMenuTable,{type ExecutionRef} from "@/components/ExecutionMenuTable";
import Modal from "@/components/Modal";
import RecipePicker from "@/components/RecipePicker";
import { actionDeleteMenu,actionSaveMenu,actionSetExecutionItem,actionSetStatus,actionValidate } from "@/app/actions";
import { exportMenuPdf } from "@/lib/exportMenuPdf";
import { exportMenuExcel } from "@/lib/exportMenuExcel";
import { formatDate } from "@/lib/dates";
import { WEEKDAYS } from "@/lib/types";
import type { Catalog,ExecutionStatus,MenuItem,MenuMetrics,MenuStatus,ValidationIssue,WeeklyMenu } from "@/lib/types";

export default function MenuDetailClient({menu,catalog,lastUsed,initialIssues,initialMetrics,generalAdmin,canRecord}:{menu:WeeklyMenu;catalog:Catalog;lastUsed:Record<string,string>;initialIssues:ValidationIssue[];initialMetrics:MenuMetrics;generalAdmin:boolean;canRecord:boolean}){
  const router=useRouter();const [,startTransition]=useTransition();
  const [items,setItems]=useState(menu.items);const [issues,setIssues]=useState(initialIssues);const [metrics,setMetrics]=useState(initialMetrics);const [status,setStatus]=useState<MenuStatus>(menu.status);const [cell,setCell]=useState<CellRef|null>(null);const [execRef,setExecRef]=useState<ExecutionRef|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [executionView,setExecutionView]=useState(false);
  const today=new Date().toISOString().slice(0,10);const started=!!menu.actual_start_date&&today>=menu.actual_start_date;
  const usedRecipeIds=useMemo(()=>items.flatMap(i=>[i.recipe_id,i.salad_recipe_id].filter(Boolean) as string[]),[items]);
  const proteinUseCounts=useMemo(()=>{const x:Record<string,number>={};items.forEach(i=>{if(i.protein_id)x[i.protein_id]=(x[i.protein_id]??0)+1});return x;},[items]);

  function revalidate(next:MenuItem[]){setItems(next);startTransition(async()=>{const r=await actionValidate({items:next,year:menu.year,week:menu.week_number,campId:menu.camp_id,arrival:menu.supply_arrival_weekday,diners:menu.diners,scheduleShiftDays:menu.schedule_shift_days??0});setIssues(r.issues);setMetrics(r.metrics);});}
  function pick(recipeId:string|null){if(!cell)return;const next=items.map(i=>{if(i.weekday!==cell.weekday||i.service!==cell.service||i.component!==cell.component)return i;if(cell.field==="salad")return {...i,salad_recipe_id:recipeId};const r=catalog.recipes.find(x=>x.id===recipeId);return {...i,recipe_id:recipeId,protein_id:r?.primary_protein_id??null,reasons:["Selección manual del administrador."]};});setCell(null);revalidate(next);}
  async function save(nextStatus:MenuStatus){
    if(nextStatus==="aprobado"&&metrics.errors>0){setMessage(`El menú tiene ${metrics.errors} error(es) críticos. Puede guardarlo como borrador, pero debe corregirlos antes de aprobar o exportar.`);return;}
    setBusy(true);try{await actionSaveMenu({id:menu.id,year:menu.year,week:menu.week_number,campId:menu.camp_id,diners:menu.diners,arrival:menu.supply_arrival_weekday,items,status:nextStatus,notes:menu.notes,seed:menu.seed,start:menu.actual_start_date,end:menu.actual_end_date,validationScore:metrics.complianceScore,varietyScore:metrics.varietyScore,scheduleShiftDays:menu.schedule_shift_days??0});setStatus(nextStatus);setMessage(metrics.errors?"Borrador guardado. Corrija las reglas críticas antes de aprobar o exportar.":"Cambios guardados.");router.refresh();}finally{setBusy(false)}}
  async function markExecution(status:ExecutionStatus){if(!execRef)return;setBusy(true);try{await actionSetExecutionItem({menuId:menu.id,weekday:execRef.weekday,service:execRef.service,component:execRef.component,field:execRef.field,status});setItems(prev=>prev.map(i=>{if(i.weekday!==execRef.weekday||i.service!==execRef.service||i.component!==execRef.component)return i;if(execRef.field==="salad")return {...i,salad_execution_status:status};if(execRef.field==="beverage")return {...i,beverage_execution_status:status};return {...i,execution_status:status};}));setExecRef(null);router.refresh();}finally{setBusy(false)}}
  const evaluated=useMemo(()=>{let ok=0,no=0,pending=0;const norm=(s:ExecutionStatus|undefined)=>s==="complies"||s==="as_planned"?"ok":s==="not_complies"||s==="replaced"?"no":"pending";for(const i of items){const statuses=[i.execution_status];if(i.component==="main"){statuses.push(i.beverage_execution_status);if(i.service!=="breakfast")statuses.push(i.salad_execution_status);}for(const s of statuses){const n=norm(s);if(n==="ok")ok++;else if(n==="no")no++;else pending++;}}return {ok,no,pending,total:ok+no+pending,pct:ok+no?Math.round(ok/(ok+no)*100):0}},[items]);
  const errorIssues=issues.filter(i=>i.level==="error");
  const hasHardErrors=metrics.errors>0;
  const activeItem=cell?items.find(i=>i.weekday===cell.weekday&&i.service===cell.service&&i.component===cell.component):null;
  const pdfInput={items,catalog,week:menu.week_number,parity:menu.parity,campId:menu.camp_id,diners:menu.diners,start:menu.actual_start_date,end:menu.actual_end_date};
  return <div className="space-y-4">
    <section className="surface no-print flex flex-wrap items-center gap-3 p-4"><span className="chip-muted">{started?"En ejecución":status}</span><span className="chip-info">Víveres: {WEEKDAYS[menu.supply_arrival_weekday].label}</span><span className="text-xs text-muted">Uso real: {formatDate(menu.actual_start_date)} → {formatDate(menu.actual_end_date)}</span><div className="ml-auto flex flex-wrap gap-2">{started?<><button className={`btn-ghost ${!executionView?"bg-corp-100":""}`} onClick={()=>setExecutionView(false)}>Editar menú</button><button className={`btn-ghost ${executionView?"bg-corp-100":""}`} onClick={()=>setExecutionView(true)}>Cumplimiento</button></>:null}{!executionView?<><button className="btn-ghost" onClick={()=>save("borrador")} disabled={busy}>Guardar</button><button className="btn-primary" onClick={()=>save("aprobado")} disabled={busy||hasHardErrors}>Aprobar</button></>:null}<button className="btn-ghost" disabled={hasHardErrors} title={hasHardErrors?"Corrija los errores críticos antes de exportar.":"Descargar menú en el formato habitual."} onClick={()=>exportMenuPdf(pdfInput)}>PDF menú</button><button className="btn-ghost" disabled={hasHardErrors} title={hasHardErrors?"Corrija los errores críticos antes de exportar.":"Descargar el mismo menú con la porción operativa vigente de cada proteína."} onClick={()=>exportMenuPdf({...pdfInput,includeOperationalPortions:true})}>PDF + porciones</button><button className="btn-ghost" disabled={hasHardErrors} title={hasHardErrors?"Corrija los errores críticos antes de exportar.":undefined} onClick={()=>exportMenuExcel({items,catalog,year:menu.year,week:menu.week_number,campName:catalog.camps.find(c=>c.id===menu.camp_id)?.name??menu.camp_id,diners:menu.diners,start:menu.actual_start_date,end:menu.actual_end_date})}>Excel</button></div></section>
    {message?<div className="notice-warn">{message}</div>:null}

    {started?<section className="rounded-xl border border-corp-200 bg-corp-100/60 p-4"><div className="flex flex-wrap items-center gap-5"><div><div className="text-xs font-semibold uppercase tracking-wide text-corp-700">Cumplimiento semanal</div><div className="mt-1 text-3xl font-semibold text-navy-900">{evaluated.pct}%</div></div><div className="text-sm text-muted"><strong className="text-emerald-700">{evaluated.ok}</strong> cumple · <strong className="text-red-700">{evaluated.no}</strong> no cumple · {evaluated.pending} pendientes</div><div className="ml-auto text-xs text-muted">Clic en cualquier componente del menú para registrar cumplimiento.</div></div></section>:<section className={`rounded-xl border px-4 py-3 ${errorIssues.length?"border-red-200 bg-red-50":"border-emerald-200 bg-emerald-50"}`}><div className="font-semibold text-navy-900">{errorIssues.length?`${errorIssues.length} error${errorIssues.length===1?"":"es"} crítico${errorIssues.length===1?"":"s"}`:"Menú válido"}</div><div className="text-xs text-muted">{errorIssues[0]?.message??"Listo para aprobar o exportar."}</div></section>}

    <section className="surface p-4 print-full">{started&&executionView?<ExecutionMenuTable items={items} catalog={catalog} onSelect={canRecord?setExecRef:undefined}/>:<MenuTable items={items} catalog={catalog} editable onCell={setCell}/>}</section>
    {!started&&generalAdmin?<div className="no-print flex justify-end"><button className="btn-danger-ghost" onClick={async()=>{if(!confirm("¿Eliminar definitivamente este menú?"))return;setBusy(true);try{await actionDeleteMenu(menu.id);router.push("/menus");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo eliminar.");}finally{setBusy(false)}}}>Eliminar menú</button></div>:null}

    <Modal open={!!execRef} onClose={()=>setExecRef(null)} title={execRef?`${WEEKDAYS[execRef.weekday].label} · ${execRef.label}`:""} subtitle={execRef?.label}><div className="grid gap-3 sm:grid-cols-2"><button className="compliance-choice compliance-ok" disabled={busy} onClick={()=>markExecution("complies")}>✓ Cumple</button><button className="compliance-choice compliance-bad" disabled={busy} onClick={()=>markExecution("not_complies")}>× No cumple</button></div></Modal>
    <Modal open={!!cell} onClose={()=>setCell(null)} wide title={cell?`${WEEKDAYS[cell.weekday].label} · ${cell.component==="soup"?"Sopa":cell.field==="salad"?"Ensalada":cell.service==="breakfast"?"Desayuno":cell.service==="lunch"?"Almuerzo":"Cena"}`:""} subtitle="Solo se pueden seleccionar preparaciones que cumplan las reglas duras del espacio.">{cell?<RecipePicker catalog={catalog} service={cell.field==="salad"?"salad":cell.component==="soup"?"soup":cell.service} weekday={cell.weekday} parity={menu.parity} arrival={menu.supply_arrival_weekday} currentId={cell.field==="salad"?activeItem?.salad_recipe_id??null:activeItem?.recipe_id??null} usedRecipeIds={usedRecipeIds} proteinUseCounts={proteinUseCounts} lastUsed={lastUsed} items={items} diners={menu.diners} onPick={pick}/>:null}</Modal>
  </div>;
}
