"use client";

import { WEEKDAYS } from "@/lib/types";
import type { Catalog, MainService, MenuItem, Weekday } from "@/lib/types";

export interface CellRef{weekday:Weekday;service:MainService;component:"main"|"soup";field:"recipe"|"salad"}
interface Props{items:MenuItem[];catalog:Catalog;editable?:boolean;onCell?:(ref:CellRef)=>void;onToggleLock?:(weekday:Weekday,service:MainService,component:"main"|"soup")=>void;highlightErrors?:Set<string>}

export default function MenuTable({items,catalog,editable=false,onCell,onToggleLock,highlightErrors}:Props){
  const recipeName=(id:string|null|undefined,fallback?:string|null)=>id?(catalog.recipes.find(r=>r.id===id)?.name??fallback??"—"):null;
  const proteinName=(id:string|null|undefined)=>id?catalog.proteins.find(p=>p.id===id)?.name??id:null;
  const get=(w:Weekday,s:MainService,c:"main"|"soup")=>items.find(i=>i.weekday===w&&i.service===s&&i.component===c);
  const key=(w:Weekday,s:MainService,c:string)=>`${w}|${s}|${c}`;
  return <div className="overflow-x-auto pb-2"><div className="planner-grid min-w-[1280px]">{WEEKDAYS.map(d=>{const b=get(d.value,"breakfast","main"),l=get(d.value,"lunch","main"),s=get(d.value,"lunch","soup"),dn=get(d.value,"dinner","main");return <section key={d.value} className="planner-day"><header className="planner-day-head"><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-corp-500">{d.short}</span><strong>{d.label}</strong></header>
    <MealBlock title="Desayuno"><RecipeCard item={b} name={recipeName(b?.recipe_id,b?.recipe_name)} protein={proteinName(b?.protein_id)} error={highlightErrors?.has(key(d.value,"breakfast","main"))} editable={editable} onClick={()=>onCell?.({weekday:d.value,service:"breakfast",component:"main",field:"recipe"})} onLock={onToggleLock?()=>onToggleLock(d.value,"breakfast","main"):undefined}/><Meta label="Bebida" value={b?.beverage??"—"}/></MealBlock>
    <MealBlock title="Almuerzo"><MiniCard label="Sopa" value={d.value===6?"No aplica":recipeName(s?.recipe_id,s?.recipe_name)??"—"} disabled={d.value===6} editable={editable} onClick={()=>d.value!==6&&onCell?.({weekday:d.value,service:"lunch",component:"soup",field:"recipe"})} locked={s?.locked} onLock={onToggleLock&&d.value!==6?()=>onToggleLock(d.value,"lunch","soup"):undefined}/><RecipeCard item={l} name={recipeName(l?.recipe_id,l?.recipe_name)} protein={proteinName(l?.protein_id)} error={highlightErrors?.has(key(d.value,"lunch","main"))} editable={editable} onClick={()=>onCell?.({weekday:d.value,service:"lunch",component:"main",field:"recipe"})} onLock={onToggleLock?()=>onToggleLock(d.value,"lunch","main"):undefined}/><MiniCard label="Ensalada" value={recipeName(l?.salad_recipe_id,l?.salad_recipe_name)??"Sin ensalada"} editable={editable} onClick={()=>onCell?.({weekday:d.value,service:"lunch",component:"main",field:"salad"})}/><Meta label="Bebida" value={l?.beverage??"—"}/></MealBlock>
    <MealBlock title="Cena"><RecipeCard item={dn} name={recipeName(dn?.recipe_id,dn?.recipe_name)} protein={proteinName(dn?.protein_id)} error={highlightErrors?.has(key(d.value,"dinner","main"))} editable={editable} onClick={()=>onCell?.({weekday:d.value,service:"dinner",component:"main",field:"recipe"})} onLock={onToggleLock?()=>onToggleLock(d.value,"dinner","main"):undefined}/><MiniCard label="Ensalada" value={recipeName(dn?.salad_recipe_id,dn?.salad_recipe_name)??"Sin ensalada"} editable={editable} onClick={()=>onCell?.({weekday:d.value,service:"dinner",component:"main",field:"salad"})}/><Meta label="Bebida" value={dn?.beverage??"—"}/></MealBlock>
  </section>})}</div><p className="mt-3 text-xs text-muted">Todos los servicios incluyen arroz por defecto, excepto preparaciones con arroz integrado.</p></div>
}
function MealBlock({title,children}:{title:string;children:React.ReactNode}){return <div className="planner-meal"><div className="planner-meal-title">{title}</div><div className="space-y-2">{children}</div></div>}
function RecipeCard({item,name,protein,error,editable,onClick,onLock}:{item?:MenuItem;name:string|null;protein:string|null;error?:boolean;editable:boolean;onClick:()=>void;onLock?:()=>void}){return <div className={`food-card ${error?"border-red-300 bg-red-50":""}`}><button type="button" disabled={!editable} onClick={onClick} className={`w-full text-left ${editable?"cursor-pointer":"cursor-default"}`}><div className="text-[13px] font-semibold leading-snug text-navy-900">{name??"Sin preparación"}</div>{protein?<span className="mt-2 inline-flex rounded-full bg-corp-100 px-2 py-0.5 text-[10px] font-semibold text-corp-700">{protein}</span>:null}</button>{onLock?<button type="button" onClick={onLock} className={`mt-2 text-[10px] font-semibold ${item?.locked?"text-corp-700":"text-muted"}`}>{item?.locked?"Bloqueado":"Bloquear"}</button>:null}</div>}
function MiniCard({label,value,editable=false,onClick,disabled=false,locked,onLock}:{label:string;value:string;editable?:boolean;onClick?:()=>void;disabled?:boolean;locked?:boolean;onLock?:()=>void}){return <div className={`mini-food ${disabled?"opacity-60":""}`}><button type="button" disabled={!editable||disabled} onClick={onClick} className="w-full text-left"><span className="block text-[9px] font-semibold uppercase tracking-[.1em] text-muted">{label}</span><span className="mt-0.5 block text-[11.5px] leading-snug text-ink">{value}</span></button>{onLock&&!disabled?<button type="button" onClick={onLock} className={`mt-1 text-[9px] font-semibold ${locked?"text-corp-700":"text-muted"}`}>{locked?"Bloqueado":"Bloquear"}</button>:null}</div>}
function Meta({label,value}:{label:string;value:string}){return <div className="px-1"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-muted">{label}</span><div className="mt-0.5 text-[10.5px] italic leading-snug text-corp-700">{value}</div></div>}
