-- Catálogo final de ensaladas IPSP 2026-09-28
-- Se conservan recetas históricas inactivas; solo estas ensaladas quedan activas.
update recipes set active=false where 'salad'=any(array(select service from recipe_services where recipe_id=recipes.id));

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-tomate-cebolla-colorada','Ensalada de tomate y cebolla colorada',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Tomate + Cebolla colorada. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-tomate-cebolla-colorada';
insert into recipe_services (recipe_id,service) values ('ens-tomate-cebolla-colorada','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-tomate-cebolla-colorada';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-tomate-zanahoria','Ensalada de tomate y zanahoria',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Tomate + Zanahoria. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-tomate-zanahoria';
insert into recipe_services (recipe_id,service) values ('ens-tomate-zanahoria','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-tomate-zanahoria';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-tomate-pimiento','Ensalada de tomate y pimiento',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Tomate + Pimiento. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-tomate-pimiento';
insert into recipe_services (recipe_id,service) values ('ens-tomate-pimiento','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-tomate-pimiento';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-tomate-cilantro','Ensalada de tomate y cilantro',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Tomate + Cilantro. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-tomate-cilantro';
insert into recipe_services (recipe_id,service) values ('ens-tomate-cilantro','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-tomate-cilantro';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-col-zanahoria','Ensalada de col y zanahoria',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Col + Zanahoria. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-col-zanahoria';
insert into recipe_services (recipe_id,service) values ('ens-col-zanahoria','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-col-zanahoria';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-col-cebolla-colorada','Ensalada de col y cebolla colorada',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Col + Cebolla colorada. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-col-cebolla-colorada';
insert into recipe_services (recipe_id,service) values ('ens-col-cebolla-colorada','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-col-cebolla-colorada';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-col-pimiento','Ensalada de col y pimiento',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Col + Pimiento. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-col-pimiento';
insert into recipe_services (recipe_id,service) values ('ens-col-pimiento','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-col-pimiento';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-col-cilantro','Ensalada de col y cilantro',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Col + Cilantro. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-col-cilantro';
insert into recipe_services (recipe_id,service) values ('ens-col-cilantro','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-col-cilantro';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-zanahoria-cebolla-blanca','Ensalada de zanahoria y cebolla blanca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Zanahoria + Cebolla blanca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-zanahoria-cebolla-blanca';
insert into recipe_services (recipe_id,service) values ('ens-zanahoria-cebolla-blanca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-zanahoria-cebolla-blanca';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-zanahoria-cilantro','Ensalada de zanahoria y cilantro',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Zanahoria + Cilantro. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-zanahoria-cilantro';
insert into recipe_services (recipe_id,service) values ('ens-zanahoria-cilantro','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-zanahoria-cilantro';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-pimiento-cebolla-colorada','Ensalada de pimiento y cebolla colorada',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Pimiento + Cebolla colorada. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-pimiento-cebolla-colorada';
insert into recipe_services (recipe_id,service) values ('ens-pimiento-cebolla-colorada','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-pimiento-cebolla-colorada';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-pimiento-albahaca','Ensalada de pimiento y albahaca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Pimiento + Albahaca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-pimiento-albahaca';
insert into recipe_services (recipe_id,service) values ('ens-pimiento-albahaca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-pimiento-albahaca';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-remolacha-cebolla-colorada','Ensalada de remolacha y cebolla colorada',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Remolacha + Cebolla colorada. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-remolacha-cebolla-colorada';
insert into recipe_services (recipe_id,service) values ('ens-remolacha-cebolla-colorada','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-remolacha-cebolla-colorada';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-remolacha-cebolla-colorada','remolacha') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-remolacha-cebolla-blanca','Ensalada de remolacha y cebolla blanca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Remolacha + Cebolla blanca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-remolacha-cebolla-blanca';
insert into recipe_services (recipe_id,service) values ('ens-remolacha-cebolla-blanca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-remolacha-cebolla-blanca';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-remolacha-cebolla-blanca','remolacha') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-coliflor-albahaca','Ensalada de coliflor y albahaca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Coliflor + Albahaca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-coliflor-albahaca';
insert into recipe_services (recipe_id,service) values ('ens-coliflor-albahaca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-coliflor-albahaca';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-coliflor-albahaca','coliflor') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-remolacha-cilantro','Ensalada de remolacha y cilantro',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Remolacha + Cilantro. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-remolacha-cilantro';
insert into recipe_services (recipe_id,service) values ('ens-remolacha-cilantro','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-remolacha-cilantro';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-remolacha-cilantro','remolacha') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-pepino-cebolla-blanca','Ensalada de pepino y cebolla blanca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Pepino + Cebolla blanca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-pepino-cebolla-blanca';
insert into recipe_services (recipe_id,service) values ('ens-pepino-cebolla-blanca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-pepino-cebolla-blanca';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-pepino-cebolla-blanca','pepino') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-pepino-rabano','Ensalada de pepino y rábano',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Pepino + Rábano. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-pepino-rabano';
insert into recipe_services (recipe_id,service) values ('ens-pepino-rabano','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-pepino-rabano';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-pepino-rabano','pepino') on conflict do nothing;
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-pepino-rabano','rabano') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-pepino-brocoli','Ensalada de pepino y brócoli',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Pepino + Brócoli. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-pepino-brocoli';
insert into recipe_services (recipe_id,service) values ('ens-pepino-brocoli','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-pepino-brocoli';
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-pepino-brocoli','pepino') on conflict do nothing;
insert into recipe_restrictive_products (recipe_id,restrictive_product_id) values ('ens-pepino-brocoli','brocoli') on conflict do nothing;

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ens-nabo-cebolla-blanca','Ensalada de nabo y cebolla blanca',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Ingredientes principales: Nabo + Cebolla blanca. Preparación simple; 2 ingredientes principales.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ens-nabo-cebolla-blanca';
insert into recipe_services (recipe_id,service) values ('ens-nabo-cebolla-blanca','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ens-nabo-cebolla-blanca';

insert into recipes (id,name,primary_protein_id,active,source,notes,base_ingredient,difficulty,cooking_method,double_fry,sunday_roast,base_qty_per_person,base_unit,protein_qty_per_person,protein_unit,rice_mode,fixed_weekday,fixed_service,only_weekday) values ('ensalada-segun-stock','Ensalada según stock',null,true,'Regla operativa IPSP · ensaladas 2026-09-28','Solo días 6 y 7 del ciclo real contado desde el día posterior a la recepción de víveres.',null,1,'Ensalada',false,false,null,null,null,null,'default',null,null,null) on conflict (id) do update set name=excluded.name, primary_protein_id=null, active=true, source=excluded.source, notes=excluded.notes, base_ingredient=null, difficulty=1, cooking_method='Ensalada', double_fry=false, sunday_roast=false, base_qty_per_person=null, base_unit=null, protein_qty_per_person=null, protein_unit=null, rice_mode='default', fixed_weekday=null, fixed_service=null, only_weekday=null;
delete from recipe_services where recipe_id='ensalada-segun-stock';
insert into recipe_services (recipe_id,service) values ('ensalada-segun-stock','salad') on conflict do nothing;
delete from recipe_restrictive_products where recipe_id='ensalada-segun-stock';

